# Generated by Django 4.2.7 on 2023-11-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0002_wallets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallets',
        ),
    ]
